// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package user

import (
	user5 "github.com/karamaru-alpha/ddd-sample/application/user/create"
	user4 "github.com/karamaru-alpha/ddd-sample/domain/model/user"
	user3 "github.com/karamaru-alpha/ddd-sample/domain/service/user"
	"github.com/karamaru-alpha/ddd-sample/infrastructure/mysql"
	user2 "github.com/karamaru-alpha/ddd-sample/infrastructure/mysql/user"
	"github.com/karamaru-alpha/ddd-sample/interfaces/controller/user"
)

// Injectors from wire.go:

// InitializeDI DI about user
func InitializeDI() user.IController {
	db := mysql.ConnectGorm()
	iRepository := user2.NewRepositoryImpl(db)
	iDomainService := user3.NewDomainService(iRepository)
	iFactory := user4.NewFactory()
	iInputPort := user5.NewInteractor(iDomainService, iRepository, iFactory)
	iController := user.NewController(iInputPort)
	return iController
}
